package compilamos.manana.partygame.game.event;

public enum DomainEventType {

    //Custom event
    FRONTEND_CUSTOM_EVENT,

    // LOBBY / ROOM
    PLAYER_JOINED,
    PLAYER_LEFT,
    PLAYER_DISCONNECTED,
    PLAYER_CONNECTED,
    HOST_CONNECTED,
    HOST_DISCONNECTED,
    HOST_SNAPSHOT,
    PLAYER_SNAPSHOT,

    // GAME
    PARTIDA_INICIADA,
    ROLES_ASIGNADOS,
    RONDA_INICIADA,
    PREGUNTA_ASIGNADA,
    RESPUESTA_ENVIADA
}
